// samples/ReactHelloWorld/frontend/src/components/GreetCard.tsx
// Copyright (c) Mythetech. Licensed under the MIT License.
import { useState } from 'react';
import { useInvoke } from '@hermes/react';
import './GreetCard.css';

function GreetCard() {
  const [name, setName] = useState('World');
  const { data, loading, error, invoke } = useInvoke<string>('greet');

  const handleGreet = async () => {
    try {
      await invoke(name);
    } catch {
      // Error captured in hook state
    }
  };

  return (
    <div className="card">
      <div className="greet-form">
        <input
          type="text"
          value={name}
          onChange={(e) => setName(e.target.value)}
          placeholder="Enter your name"
        />
        <button onClick={handleGreet} disabled={loading}>
          {loading ? 'Greeting...' : 'Greet from C#'}
        </button>
      </div>
      {data && <p className="output">{data}</p>}
      {error && <p className="output error">{error.message}</p>}
    </div>
  );
}

export default GreetCard;

// samples/SvelteHelloWorld/frontend/src/lib/GreetCard.svelte
<!-- Copyright (c) Mythetech. Licensed under the MIT License. -->
<script lang="ts">
  import { bridge } from '@hermes/bridge';
  import { hermesConnected } from '@hermes/svelte';

  let name = $state('World');
  let output = $state('');

  async function greet() {
    if (!$hermesConnected) {
      output = `Hello from JavaScript, ${name}! (bridge not available)`;
      return;
    }

    try {
      output = await bridge.invoke<string>('greet', name);
    } catch (e) {
      output = `Error: ${e instanceof Error ? e.message : e}`;
    }
  }
</script>

<div class="card">
  <input type="text" bind:value={name} placeholder="Enter your name" />
  <button onclick={greet}>Greet from C#</button>
  {#if output}
    <p class="output">{output}</p>
  {/if}
</div>
