// samples/SvelteHelloWorld/frontend/src/lib/SystemInfo.svelte
<!-- Copyright (c) Mythetech. Licensed under the MIT License. -->
<script lang="ts">
  import { createInvokeStore } from '@hermes/svelte';

  const runtime = createInvokeStore<string>('getRuntime');
  const platform = createInvokeStore<string>('getPlatform');
</script>

<div class="card">
  <h2>System Info</h2>
  <p>
    Runtime:
    {#if $runtime.loading}
      <span class="loading">Loading...</span>
    {:else if $runtime.error}
      <span>N/A ({$runtime.error.message})</span>
    {:else}
      <span>{$runtime.data}</span>
    {/if}
  </p>
  <p>
    Platform:
    {#if $platform.loading}
      <span class="loading">Loading...</span>
    {:else if $platform.error}
      <span>N/A ({$platform.error.message})</span>
    {:else}
      <span>{$platform.data}</span>
    {/if}
  </p>
</div>

// samples/ReactHelloWorld/frontend/src/components/SystemInfo.tsx
// Copyright (c) Mythetech. Licensed under the MIT License.
import { useInvoke } from '@hermes/react';
import './SystemInfo.css';

function SystemInfo() {
  const runtime = useInvoke<string>('getRuntime');
  const platform = useInvoke<string>('getPlatform');

  return (
    <div className="card system-info">
      <h2>System Info</h2>
      <p>
        Runtime:{' '}
        <span className="info-value">
          {runtime.loading ? 'Loading...' : runtime.data ?? 'N/A'}
        </span>
      </p>
      <p>
        Platform:{' '}
        <span className="info-value">
          {platform.loading ? 'Loading...' : platform.data ?? 'N/A'}
        </span>
      </p>
    </div>
  );
}

export default SystemInfo;
