// samples/SvelteHelloWorld/frontend/src/App.svelte
<!-- Copyright (c) Mythetech. Licensed under the MIT License. -->
<script lang="ts">
  import { hermesConnected } from '@hermes/svelte';
  import GreetCard from './lib/GreetCard.svelte';
  import SystemInfo from './lib/SystemInfo.svelte';
  import LiveTicker from './lib/LiveTicker.svelte';
</script>

<h1>Hermes + Svelte</h1>
<p class="subtitle">Svelte SPA running in a native desktop window</p>

<p>
  Hermes Bridge:
  {#if $hermesConnected}
    <span class="status connected">Connected</span>
  {:else}
    <span class="status disconnected">Not available (running in browser)</span>
  {/if}
</p>

<GreetCard />
<SystemInfo />
<LiveTicker />

// samples/ReactHelloWorld/frontend/src/App.tsx
// Copyright (c) Mythetech. Licensed under the MIT License.
import { bridge } from '@hermes/bridge';
import GreetCard from './components/GreetCard';
import SystemInfo from './components/SystemInfo';
import './App.css';

function App() {
  return (
    <div className="app">
      <h1>Hermes Web</h1>
      <p className="subtitle">
        React + TypeScript SPA running in a native desktop window
      </p>
      <GreetCard />
      <SystemInfo />
      <p className="bridge-status">
        Hermes Bridge: {bridge.isHermes ? 'Connected' : 'Not available (running in browser)'}
      </p>
    </div>
  );
}

export default App;
